"""
Research Question Refinement Stage with Human-in-the-Loop
This script uses two specialized agents to refine research questions based on literature.

Agents:
- Ideator: Generates research concepts and ideas from literature
- Refiner: Formulates precise, actionable research questions

Input: Literature results from 1-SourcingStage.py (CSV file)
Output: Refined research questions with two-round feedback process
"""

import os
import json
from typing import List, Dict, Optional
from datetime import datetime
from dotenv import load_dotenv
import pandas as pd
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field

# Load environment variables
load_dotenv()


class ResearchConcept(BaseModel):
    """Model for a research concept generated by Ideator."""
    concept_title: str = Field(description="Short title for the concept")
    description: str = Field(description="Detailed description of the concept")
    key_themes: List[str] = Field(description="Key themes or topics")
    literature_support: List[str] = Field(description="Paper titles that support this concept")
    novelty_score: Optional[float] = Field(description="Novelty score (0-1)", default=None)


class ResearchQuestion(BaseModel):
    """Model for a refined research question."""
    question: str = Field(description="The research question")
    rationale: str = Field(description="Why this question is important")
    methodology_hints: List[str] = Field(description="Suggested methodological approaches")
    related_concepts: List[str] = Field(description="Related concept titles")
    feasibility_score: Optional[float] = Field(description="Feasibility score (0-1)", default=None)


class ConceptList(BaseModel):
    """Model for a list of research concepts."""
    concepts: List[ResearchConcept] = Field(description="List of research concepts")


class QuestionList(BaseModel):
    """Model for a list of research questions."""
    questions: List[ResearchQuestion] = Field(description="List of research questions")


class HumanFeedback(BaseModel):
    """Model for human feedback on concepts/questions."""
    round_number: int = Field(description="Feedback round number")
    promising_items: List[str] = Field(description="Promising concepts/questions", default_factory=list)
    weak_items: List[str] = Field(description="Weak or unfeasible items", default_factory=list)
    missing_angles: List[str] = Field(description="Missing perspectives or angles", default_factory=list)
    focus_directions: List[str] = Field(description="Directions to focus on", default_factory=list)
    comments: str = Field(description="General comments and guidance", default="")


class BaseRefinementAgent:
    """Base class for refinement agents."""
    
    def __init__(self, agent_name: str, openai_api_key: str):
        self.agent_name = agent_name
        self.api_key = openai_api_key
        self.llm = ChatOpenAI(
            model="gpt-4",
            temperature=0.7,  # Higher temperature for creativity
            openai_api_key=self.api_key
        )
    
    def process(self, literature_df: pd.DataFrame, feedback: Optional[HumanFeedback] = None):
        """Process literature and generate output. To be implemented by subclasses."""
        raise NotImplementedError


class Ideator(BaseRefinementAgent):
    """Agent that generates research concepts from literature."""
    
    def __init__(self, openai_api_key: str):
        super().__init__("Ideator", openai_api_key)
    
    def generate_concepts(
        self, 
        literature_df: pd.DataFrame, 
        feedback: Optional[HumanFeedback] = None,
        num_concepts: int = 8
    ) -> List[ResearchConcept]:
        """Generate research concepts from literature."""
        
        print(f"\n[{self.agent_name}] Generating research concepts from {len(literature_df)} papers...")
        
        # Prepare literature summary
        lit_summary = self._prepare_literature_summary(literature_df)
        
        # Prepare feedback context
        feedback_context = ""
        if feedback:
            feedback_context = f"""
            Previous feedback:
            - Promising concepts: {', '.join(feedback.promising_items[:5])}
            - Weak concepts: {', '.join(feedback.weak_items[:3])}
            - Missing angles: {', '.join(feedback.missing_angles)}
            - Focus directions: {', '.join(feedback.focus_directions)}
            - Comments: {feedback.comments}
            """
        
        parser = PydanticOutputParser(pydantic_object=ConceptList)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are Ideator, an expert at identifying novel research concepts from academic literature. You must respond with valid JSON only."),
            ("user", """Based on the following literature, generate innovative research concepts.
            
            Literature Summary:
            {literature_summary}
            
            {feedback_context}
            
            Generate {num_concepts} research concepts that:
            - Identify gaps in current research
            - Synthesize insights across multiple papers
            - Propose novel angles or perspectives
            - Are grounded in the literature provided
            - Have potential for significant contribution
            
            For each concept, provide:
            - A clear, concise title
            - Detailed description (2-3 sentences)
            - Key themes (3-5 themes)
            - Supporting literature (list 2-4 paper titles from the summary)
            
            Respond with a JSON object containing:
            - "concepts": array of concept objects, each with "concept_title", "description", "key_themes", "literature_support"
            
            Example format:
            {{
              "concepts": [
                {{
                  "concept_title": "Concept Title",
                  "description": "Detailed description...",
                  "key_themes": ["theme1", "theme2", "theme3"],
                  "literature_support": ["Paper A", "Paper B"]
                }}
              ]
            }}
            
            Respond with ONLY the JSON object, no other text.
            """)
        ])
        
        chain = prompt | self.llm | parser
        result = chain.invoke({
            "literature_summary": lit_summary,
            "feedback_context": feedback_context,
            "num_concepts": num_concepts
        })
        
        # Score novelty
        concepts = result.concepts
        for i, concept in enumerate(concepts):
            concept.novelty_score = self._score_novelty(concept, literature_df)
        
        print(f"[{self.agent_name}] Generated {len(concepts)} concepts")
        return concepts
    
    def _prepare_literature_summary(self, df: pd.DataFrame, max_papers: int = 30) -> str:
        """Prepare a summary of literature for the prompt."""
        # Sort by relevance score if available
        if 'relevance_score' in df.columns:
            df_sorted = df.sort_values('relevance_score', ascending=False).head(max_papers)
        else:
            df_sorted = df.head(max_papers)
        
        summary_parts = []
        for idx, row in df_sorted.iterrows():
            paper_summary = f"""
Paper {idx + 1}: {row.get('title', 'N/A')}
Authors: {row.get('authors', 'N/A')}
Year: {row.get('year', 'N/A')}
Abstract: {row.get('abstract', 'N/A')[:300]}...
"""
            summary_parts.append(paper_summary)
        
        return "\n".join(summary_parts)
    
    def _score_novelty(self, concept: ResearchConcept, literature_df: pd.DataFrame) -> float:
        """Score the novelty of a concept (placeholder - could use embeddings)."""
        # Simple heuristic: more themes = potentially more novel
        base_score = min(len(concept.key_themes) / 5.0, 1.0)
        return round(base_score, 2)


class Refiner(BaseRefinementAgent):
    """Agent that formulates precise research questions from concepts."""
    
    def __init__(self, openai_api_key: str):
        super().__init__("Refiner", openai_api_key)
    
    def formulate_questions(
        self,
        concepts: List[ResearchConcept],
        literature_df: pd.DataFrame,
        feedback: Optional[HumanFeedback] = None,
        num_questions: int = 6
    ) -> List[ResearchQuestion]:
        """Formulate research questions from concepts."""
        
        print(f"\n[{self.agent_name}] Formulating research questions from {len(concepts)} concepts...")
        
        # Prepare concepts summary
        concepts_summary = self._prepare_concepts_summary(concepts)
        
        # Prepare feedback context
        feedback_context = ""
        if feedback:
            feedback_context = f"""
            Previous feedback:
            - Promising questions: {', '.join(feedback.promising_items[:5])}
            - Weak questions: {', '.join(feedback.weak_items[:3])}
            - Missing angles: {', '.join(feedback.missing_angles)}
            - Focus directions: {', '.join(feedback.focus_directions)}
            - Comments: {feedback.comments}
            """
        
        parser = PydanticOutputParser(pydantic_object=QuestionList)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are Refiner, an expert at formulating precise, actionable research questions. You must respond with valid JSON only."),
            ("user", """Based on the following research concepts, formulate specific research questions.
            
            Research Concepts:
            {concepts_summary}
            
            {feedback_context}
            
            Generate {num_questions} research questions that are:
            - Specific and well-defined
            - Answerable through empirical or theoretical research
            - Novel and contribute to the field
            - Feasible with available methods
            - Grounded in the concepts provided
            
            For each question:
            - State the question clearly and concisely
            - Provide rationale (why it's important)
            - Suggest 2-4 methodological approaches
            - Link to related concept titles
            
            Respond with a JSON object containing:
            - "questions": array of question objects, each with "question", "rationale", "methodology_hints", "related_concepts"
            
            Example format:
            {{
              "questions": [
                {{
                  "question": "How does X affect Y under conditions Z?",
                  "rationale": "This question addresses a gap...",
                  "methodology_hints": ["Agent-based modeling", "Econometric analysis"],
                  "related_concepts": ["Concept Title 1", "Concept Title 2"]
                }}
              ]
            }}
            
            Respond with ONLY the JSON object, no other text.
            """)
        ])
        
        chain = prompt | self.llm | parser
        result = chain.invoke({
            "concepts_summary": concepts_summary,
            "feedback_context": feedback_context,
            "num_questions": num_questions
        })
        
        # Score feasibility
        questions = result.questions
        for question in questions:
            question.feasibility_score = self._score_feasibility(question)
        
        print(f"[{self.agent_name}] Formulated {len(questions)} questions")
        return questions
    
    def _prepare_concepts_summary(self, concepts: List[ResearchConcept]) -> str:
        """Prepare a summary of concepts for the prompt."""
        summary_parts = []
        for i, concept in enumerate(concepts):
            concept_summary = f"""
Concept {i + 1}: {concept.concept_title}
Description: {concept.description}
Key Themes: {', '.join(concept.key_themes)}
Literature Support: {', '.join(concept.literature_support)}
Novelty Score: {concept.novelty_score}
"""
            summary_parts.append(concept_summary)
        
        return "\n".join(summary_parts)
    
    def _score_feasibility(self, question: ResearchQuestion) -> float:
        """Score the feasibility of a question (placeholder)."""
        # Simple heuristic: more methodology hints = more feasible
        base_score = min(len(question.methodology_hints) / 4.0, 1.0)
        return round(base_score, 2)


class RefinementOrchestrator:
    """Orchestrates the two-agent refinement process with human feedback."""
    
    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError("OPENAI_API_KEY not found in environment variables")
        
        self.ideator = Ideator(self.api_key)
        self.refiner = Refiner(self.api_key)
        
        self.all_concepts = []
        self.all_questions = []
        self.round_results = {}
    
    def load_literature(self, csv_path: str) -> pd.DataFrame:
        """Load literature from CSV file."""
        print(f"\n[Orchestrator] Loading literature from {csv_path}...")
        df = pd.read_csv(csv_path)
        print(f"[Orchestrator] Loaded {len(df)} papers")
        return df
    
    def run_refinement_round(
        self,
        literature_df: pd.DataFrame,
        round_number: int,
        feedback: Optional[HumanFeedback] = None,
        num_concepts: int = 8,
        num_questions: int = 6
    ) -> Tuple[List[ResearchConcept], List[ResearchQuestion]]:
        """Run one round of refinement (Ideator → Refiner)."""
        
        print(f"\n{'='*70}")
        print(f"ROUND {round_number}: Research Question Refinement")
        print(f"{'='*70}")
        
        # Step 1: Ideator generates concepts
        concepts = self.ideator.generate_concepts(
            literature_df=literature_df,
            feedback=feedback,
            num_concepts=num_concepts
        )
        
        # Step 2: Refiner formulates questions from concepts
        questions = self.refiner.formulate_questions(
            concepts=concepts,
            literature_df=literature_df,
            feedback=feedback,
            num_questions=num_questions
        )
        
        # Store results
        self.round_results[round_number] = {
            'concepts': concepts,
            'questions': questions
        }
        
        # Add to all results
        self.all_concepts.extend(concepts)
        self.all_questions.extend(questions)
        
        return concepts, questions
    
    def print_concepts(self, round_number: int, top_n: int = 10):
        """Print concepts from a specific round."""
        if round_number not in self.round_results:
            print(f"No results for round {round_number}")
            return
        
        concepts = self.round_results[round_number]['concepts']
        
        print(f"\n{'='*70}")
        print(f"ROUND {round_number} - RESEARCH CONCEPTS (Top {min(top_n, len(concepts))})")
        print(f"{'='*70}\n")
        
        # Sort by novelty score
        sorted_concepts = sorted(concepts, key=lambda x: x.novelty_score or 0, reverse=True)
        
        for i, concept in enumerate(sorted_concepts[:top_n], 1):
            print(f"{i}. {concept.concept_title}")
            print(f"   Novelty: {concept.novelty_score}")
            print(f"   Description: {concept.description}")
            print(f"   Key Themes: {', '.join(concept.key_themes)}")
            print(f"   Literature Support: {', '.join(concept.literature_support[:3])}")
            print()
    
    def print_questions(self, round_number: int, top_n: int = 10):
        """Print questions from a specific round."""
        if round_number not in self.round_results:
            print(f"No results for round {round_number}")
            return
        
        questions = self.round_results[round_number]['questions']
        
        print(f"\n{'='*70}")
        print(f"ROUND {round_number} - RESEARCH QUESTIONS (Top {min(top_n, len(questions))})")
        print(f"{'='*70}\n")
        
        # Sort by feasibility score
        sorted_questions = sorted(questions, key=lambda x: x.feasibility_score or 0, reverse=True)
        
        for i, question in enumerate(sorted_questions[:top_n], 1):
            print(f"{i}. {question.question}")
            print(f"   Feasibility: {question.feasibility_score}")
            print(f"   Rationale: {question.rationale}")
            print(f"   Methodologies: {', '.join(question.methodology_hints)}")
            print(f"   Related Concepts: {', '.join(question.related_concepts)}")
            print()
    
    def collect_human_feedback(self, round_number: int) -> HumanFeedback:
        """Collect human feedback interactively."""
        print(f"\n{'='*70}")
        print(f"FEEDBACK COLLECTION - Round {round_number}")
        print(f"{'='*70}\n")
        
        print("Please provide feedback on the concepts and questions generated.")
        print("Press Enter to skip any field.\n")
        
        promising = input("Enter promising concepts/questions (comma-separated): ").strip()
        promising_items = [x.strip() for x in promising.split(",")] if promising else []
        
        weak = input("Enter weak or unfeasible items (comma-separated): ").strip()
        weak_items = [x.strip() for x in weak.split(",")] if weak else []
        
        missing = input("Enter missing angles or perspectives (comma-separated): ").strip()
        missing_angles = [x.strip() for x in missing.split(",")] if missing else []
        
        focus = input("Enter directions to focus on (comma-separated): ").strip()
        focus_directions = [x.strip() for x in focus.split(",")] if focus else []
        
        comments = input("General comments: ").strip()
        
        feedback = HumanFeedback(
            round_number=round_number,
            promising_items=promising_items,
            weak_items=weak_items,
            missing_angles=missing_angles,
            focus_directions=focus_directions,
            comments=comments
        )
        
        # Save feedback to JSON
        feedback_file = f"round{round_number}_refinement_feedback.json"
        with open(feedback_file, 'w') as f:
            json.dump(feedback.model_dump(), f, indent=2)
        
        print(f"\n[Orchestrator] Feedback saved to {feedback_file}")
        
        return feedback
    
    def save_results(self, filename: str, round_number: Optional[int] = None):
        """Save concepts and questions to JSON file."""
        if round_number:
            # Save specific round
            if round_number not in self.round_results:
                print(f"No results for round {round_number}")
                return
            
            data = {
                'round': round_number,
                'concepts': [c.model_dump() for c in self.round_results[round_number]['concepts']],
                'questions': [q.model_dump() for q in self.round_results[round_number]['questions']]
            }
            output_file = f"round{round_number}_{filename}"
        else:
            # Save all rounds
            data = {
                'all_concepts': [c.model_dump() for c in self.all_concepts],
                'all_questions': [q.model_dump() for q in self.all_questions],
                'by_round': {
                    str(rnd): {
                        'concepts': [c.model_dump() for c in results['concepts']],
                        'questions': [q.model_dump() for q in results['questions']]
                    }
                    for rnd, results in self.round_results.items()
                }
            }
            output_file = filename
        
        with open(output_file, 'w') as f:
            json.dump(data, f, indent=2)
        
        print(f"[Orchestrator] Results saved to {output_file}")


def main():
    """Main function with two-round refinement process."""
    
    # Configuration
    literature_csv = "literature_results_all_rounds.csv"  # Output from Stage 1
    
    print("="*70)
    print("STARTING TWO-ROUND RESEARCH QUESTION REFINEMENT")
    print("="*70)
    
    # Initialize orchestrator
    orchestrator = RefinementOrchestrator()
    
    # Load literature from Stage 1
    try:
        literature_df = orchestrator.load_literature(literature_csv)
    except FileNotFoundError:
        print(f"\nError: {literature_csv} not found!")
        print("Please run 1-SourcingStage.py first to generate literature results.")
        return
    
    # ROUND 1: Initial concept generation and question formulation
    concepts1, questions1 = orchestrator.run_refinement_round(
        literature_df=literature_df,
        round_number=1,
        feedback=None,
        num_concepts=8,
        num_questions=6
    )
    
    # Display Round 1 results
    orchestrator.print_concepts(round_number=1, top_n=8)
    orchestrator.print_questions(round_number=1, top_n=6)
    
    # Save Round 1 results
    orchestrator.save_results("refinement_results.json", round_number=1)
    
    # Collect human feedback
    feedback = orchestrator.collect_human_feedback(round_number=1)
    
    # ROUND 2: Refined concepts and questions based on feedback
    concepts2, questions2 = orchestrator.run_refinement_round(
        literature_df=literature_df,
        round_number=2,
        feedback=feedback,
        num_concepts=8,
        num_questions=6
    )
    
    # Display Round 2 results
    orchestrator.print_concepts(round_number=2, top_n=8)
    orchestrator.print_questions(round_number=2, top_n=6)
    
    # Save Round 2 results
    orchestrator.save_results("refinement_results.json", round_number=2)
    
    # Save all results
    orchestrator.save_results("refinement_results_all_rounds.json")
    
    # Final summary
    print(f"\n{'='*70}")
    print("FINAL SUMMARY")
    print(f"{'='*70}")
    print(f"Round 1: {len(concepts1)} concepts, {len(questions1)} questions")
    print(f"Round 2: {len(concepts2)} concepts, {len(questions2)} questions")
    print(f"Total unique concepts: {len(orchestrator.all_concepts)}")
    print(f"Total unique questions: {len(orchestrator.all_questions)}")
    
    print(f"\n{'='*70}")
    print("PROCESS COMPLETE")
    print(f"{'='*70}")
    print("Files created:")
    print("  - round1_refinement_results.json")
    print("  - round1_refinement_feedback.json")
    print("  - round2_refinement_results.json")
    print("  - refinement_results_all_rounds.json")


if __name__ == "__main__":
    main()
