"""
Calibration Stage - Automated Mode (No Firecrawl, No HITL)
This script calibrates model parameters based on empirical targets and benchmarks.

Pipeline:
1. Calibrator: Extract empirical targets, perform empirical alignment, calibrate parameters

Input: Formal mathematical models from Stage 2 (model_design_output.json)
Output: Calibrated model with parameter values and fit metrics
"""

import os
import json
from typing import List, Dict, Optional, Tuple
from datetime import datetime
from dotenv import load_dotenv
import pandas as pd
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field

# Load environment variables
load_dotenv()


# ========== DATA MODELS ==========

class FormalMathematicalModel(BaseModel):
    """Model for formal mathematical model from Stage 2 (simplified)."""
    model_title: str
    model_summary: str
    based_on_framework: str
    variables: List[Dict]
    parameters: List[Dict]
    equations: List[Dict]
    constraints: List[Dict]
    dynamics: Dict
    equilibrium: Dict
    solution_method: Dict


class EmpiricalTarget(BaseModel):
    """Model for an empirical target or moment."""
    target_id: str = Field(description="Unique target identifier")
    target_name: str = Field(description="Name of the target")
    target_type: str = Field(description="Type: moment, ratio, elasticity, correlation, volatility")
    description: str = Field(description="Description of what this measures")
    empirical_value: float = Field(description="Empirical value from data/literature")
    empirical_source: str = Field(description="Source of empirical value")
    standard_error: Optional[float] = Field(description="Standard error if available", default=None)
    related_variables: List[str] = Field(description="Model variables related to this target")
    related_parameters: List[str] = Field(description="Parameters that affect this target")
    importance: str = Field(description="High/Medium/Low importance for calibration")


class CalibrationStrategy(BaseModel):
    """Model for calibration strategy."""
    strategy_type: str = Field(description="Type: direct, indirect, SMM, GMM, maximum_likelihood")
    description: str = Field(description="Description of the strategy")
    parameters_to_calibrate: List[str] = Field(description="Parameter symbols to calibrate")
    targets_to_match: List[str] = Field(description="Target IDs to match")
    calibration_order: List[str] = Field(description="Order of parameter calibration")
    identification_notes: str = Field(description="Notes on parameter identification")


class CalibratedParameter(BaseModel):
    """Model for a calibrated parameter."""
    parameter_symbol: str = Field(description="Parameter symbol")
    parameter_name: str = Field(description="Parameter name")
    calibrated_value: float = Field(description="Calibrated value")
    calibration_method: str = Field(description="How it was calibrated")
    target_matched: Optional[str] = Field(description="Target matched (if applicable)", default="")
    literature_range: str = Field(description="Typical range in literature")
    justification: str = Field(description="Justification for this value")
    sensitivity: str = Field(description="High/Medium/Low sensitivity")


class ModelMoment(BaseModel):
    """Model for a moment generated by the calibrated model."""
    moment_name: str = Field(description="Name of the moment")
    model_value: float = Field(description="Value from calibrated model")
    empirical_value: float = Field(description="Empirical target value")
    absolute_error: float = Field(description="Absolute error")
    relative_error: float = Field(description="Relative error (percentage)")
    fit_quality: str = Field(description="Excellent/Good/Fair/Poor")


class FitMetrics(BaseModel):
    """Model for overall fit metrics."""
    total_targets: int = Field(description="Total number of targets")
    targets_matched: int = Field(description="Number of well-matched targets")
    mean_absolute_error: float = Field(description="Mean absolute error across targets")
    mean_relative_error: float = Field(description="Mean relative error (percentage)")
    rmse: float = Field(description="Root mean squared error")
    fit_score: float = Field(description="Overall fit score (0-1)")
    fit_assessment: str = Field(description="Overall assessment")


class CalibratedModel(BaseModel):
    """Model for the complete calibrated model."""
    model_title: str = Field(description="Title of the calibrated model")
    based_on_model: str = Field(description="Source formal model title")
    calibration_summary: str = Field(description="Summary of calibration")
    
    # Calibration components
    empirical_targets: List[EmpiricalTarget] = Field(description="Empirical targets")
    calibration_strategy: CalibrationStrategy = Field(description="Calibration strategy")
    calibrated_parameters: List[CalibratedParameter] = Field(description="Calibrated parameters")
    model_moments: List[ModelMoment] = Field(description="Model-generated moments")
    fit_metrics: FitMetrics = Field(description="Fit metrics")
    
    # Additional information
    calibration_notes: str = Field(description="Additional calibration notes")
    robustness_checks: List[str] = Field(description="Suggested robustness checks")
    next_steps: List[str] = Field(description="Next steps for model implementation")
    
    # Metadata
    metadata: Dict = Field(description="Calibration metadata", default_factory=dict)


class CalibrationOutput(BaseModel):
    """Model for the complete calibration stage output."""
    formal_models: List[FormalMathematicalModel] = Field(description="Input formal models")
    calibrated_models: List[CalibratedModel] = Field(description="Calibrated models")
    metadata: Dict = Field(description="Output metadata", default_factory=dict)


# ========== AGENT ==========

class Calibrator:
    """Agent for calibrating model parameters using empirical targets."""
    
    def __init__(self, openai_api_key: str):
        self.agent_name = "Calibrator"
        self.api_key = openai_api_key
        self.llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=0.3,
            openai_api_key=self.api_key
        )
    
    def calibrate_model(
        self,
        formal_model: FormalMathematicalModel
    ) -> CalibratedModel:
        """Calibrate a formal mathematical model."""
        
        print(f"\n[{self.agent_name}] Calibrating model:")
        print(f"  {formal_model.model_title}")
        
        # Step 1: Extract empirical targets
        print(f"  Step 1: Extracting empirical targets and benchmarks...")
        empirical_targets = self._extract_empirical_targets(formal_model)
        
        # Step 2: Design calibration strategy
        print(f"  Step 2: Designing calibration strategy...")
        calibration_strategy = self._design_calibration_strategy(formal_model, empirical_targets)
        
        # Step 3: Calibrate parameters
        print(f"  Step 3: Calibrating parameters...")
        calibrated_parameters = self._calibrate_parameters(
            formal_model,
            empirical_targets,
            calibration_strategy
        )
        
        # Step 4: Generate model moments
        print(f"  Step 4: Generating model moments...")
        model_moments = self._generate_model_moments(
            formal_model,
            calibrated_parameters,
            empirical_targets
        )
        
        # Step 5: Compute fit metrics
        print(f"  Step 5: Computing fit metrics...")
        fit_metrics = self._compute_fit_metrics(model_moments, empirical_targets)
        
        # Step 6: Synthesize calibrated model
        print(f"  Step 6: Synthesizing calibrated model...")
        calibrated_model = self._synthesize_calibrated_model(
            formal_model,
            empirical_targets,
            calibration_strategy,
            calibrated_parameters,
            model_moments,
            fit_metrics
        )
        
        print(f"[{self.agent_name}] Calibration complete: Fit score = {fit_metrics.fit_score:.3f}")
        return calibrated_model
    
    def _extract_empirical_targets(
        self,
        formal_model: FormalMathematicalModel
    ) -> List[EmpiricalTarget]:
        """Extract empirical targets and benchmarks."""
        
        # Prepare context
        params_text = "\n".join([
            f"- {p.get('parameter_symbol', '')}: {p.get('parameter_name', '')} (Range: {p.get('typical_range', '')})"
            for p in formal_model.parameters[:10]
        ])
        
        vars_text = "\n".join([
            f"- {v.get('variable_symbol', '')}: {v.get('variable_name', '')}"
            for v in formal_model.variables[:15]
        ])
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are an expert at identifying empirical targets for economic model calibration."),
            ("user", """Identify 8-12 empirical targets/moments for calibrating this model.

Model: {model_title}
Approach: {approach}

Parameters:
{parameters}

Variables:
{variables}

For each target, provide:
- target_id: Short ID (e.g., "T1", "T2")
- target_name: Name (e.g., "Capital-output ratio", "Labor share")
- target_type: moment, ratio, elasticity, correlation, or volatility
- description: What this measures
- empirical_value: Typical value from literature (use realistic numbers)
- empirical_source: Source (e.g., "US data 1960-2020", "OECD average")
- standard_error: Standard error if known (or null)
- related_variables: Model variable symbols
- related_parameters: Parameter symbols that affect this
- importance: High, Medium, or Low

Return as JSON with "targets" array.
Example: {{
  "targets": [
    {{
      "target_id": "T1",
      "target_name": "Capital-output ratio",
      "target_type": "ratio",
      "description": "Steady state capital to output ratio",
      "empirical_value": 2.5,
      "empirical_source": "US data 1960-2020, average K/Y",
      "standard_error": 0.1,
      "related_variables": ["K", "Y"],
      "related_parameters": ["alpha", "delta", "beta"],
      "importance": "High"
    }}
  ]
}}

Respond with ONLY the JSON object, no other text.
""")
        ])
        
        chain = prompt | self.llm
        
        try:
            result = chain.invoke({
                "model_title": formal_model.model_title,
                "approach": formal_model.solution_method.get('solution_approach', 'Unknown'),
                "parameters": params_text,
                "variables": vars_text
            })
            
            data = json.loads(result.content)
            targets = [EmpiricalTarget(**t) for t in data.get("targets", [])]
            
            return targets
        
        except Exception as e:
            print(f"    Error extracting targets: {e}")
            return []
    
    def _design_calibration_strategy(
        self,
        formal_model: FormalMathematicalModel,
        empirical_targets: List[EmpiricalTarget]
    ) -> CalibrationStrategy:
        """Design calibration strategy."""
        
        params_text = "\n".join([
            f"- {p.get('parameter_symbol', '')}: {p.get('parameter_name', '')}"
            for p in formal_model.parameters[:10]
        ])
        
        targets_text = "\n".join([
            f"- {t.target_id}: {t.target_name} (Importance: {t.importance})"
            for t in empirical_targets
        ])
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are an expert at designing calibration strategies for economic models."),
            ("user", """Design a calibration strategy for this model.

Model: {model_title}

Parameters:
{parameters}

Targets:
{targets}

Provide:
- strategy_type: direct, indirect, SMM, GMM, or maximum_likelihood
- description: Description of the strategy (2-3 sentences)
- parameters_to_calibrate: List of parameter symbols to calibrate
- targets_to_match: List of target IDs to match
- calibration_order: Ordered list of parameters (which to calibrate first)
- identification_notes: Notes on how parameters are identified

Return as JSON.
Example: {{
  "strategy_type": "direct",
  "description": "Use direct calibration for easily identifiable parameters, then indirect calibration for remaining parameters by matching model moments to empirical targets.",
  "parameters_to_calibrate": ["beta", "sigma", "alpha", "delta"],
  "targets_to_match": ["T1", "T2", "T3", "T4"],
  "calibration_order": ["beta", "delta", "alpha", "sigma"],
  "identification_notes": "Beta identified from interest rate, delta from investment rate, alpha from labor share, sigma from consumption volatility."
}}

Respond with ONLY the JSON object, no other text.
""")
        ])
        
        chain = prompt | self.llm
        
        try:
            result = chain.invoke({
                "model_title": formal_model.model_title,
                "parameters": params_text,
                "targets": targets_text
            })
            
            data = json.loads(result.content)
            strategy = CalibrationStrategy(**data)
            
            return strategy
        
        except Exception as e:
            print(f"    Error designing strategy: {e}")
            return CalibrationStrategy(
                strategy_type="direct",
                description="Standard calibration approach",
                parameters_to_calibrate=[],
                targets_to_match=[],
                calibration_order=[],
                identification_notes=""
            )
    
    def _calibrate_parameters(
        self,
        formal_model: FormalMathematicalModel,
        empirical_targets: List[EmpiricalTarget],
        calibration_strategy: CalibrationStrategy
    ) -> List[CalibratedParameter]:
        """Calibrate model parameters."""
        
        params_text = "\n".join([
            f"- {p.get('parameter_symbol', '')}: {p.get('parameter_name', '')} (Range: {p.get('typical_range', '')})"
            for p in formal_model.parameters
        ])
        
        targets_text = "\n".join([
            f"- {t.target_id}: {t.target_name} = {t.empirical_value} (from {t.empirical_source})"
            for t in empirical_targets
        ])
        
        strategy_text = f"""
Strategy: {calibration_strategy.strategy_type}
Order: {' -> '.join(calibration_strategy.calibration_order)}
{calibration_strategy.identification_notes}
        """.strip()
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are an expert at calibrating parameters for economic models."),
            ("user", """Calibrate the parameters for this model based on empirical targets.

Model: {model_title}

Parameters:
{parameters}

Empirical Targets:
{targets}

Calibration Strategy:
{strategy}

For each parameter to calibrate, provide:
- parameter_symbol: Symbol
- parameter_name: Name
- calibrated_value: Calibrated value (realistic number)
- calibration_method: How it was calibrated
- target_matched: Target ID matched (if applicable)
- literature_range: Typical range
- justification: Justification for this value
- sensitivity: High, Medium, or Low

Return as JSON with "calibrated_parameters" array.
Example: {{
  "calibrated_parameters": [
    {{
      "parameter_symbol": "beta",
      "parameter_name": "Discount factor",
      "calibrated_value": 0.96,
      "calibration_method": "Directly set to match annual interest rate of 4%",
      "target_matched": "T1",
      "literature_range": "[0.95, 0.99]",
      "justification": "Standard value in macro literature, implies 4% annual discount rate",
      "sensitivity": "Medium"
    }}
  ]
}}

Respond with ONLY the JSON object, no other text.
""")
        ])
        
        chain = prompt | self.llm
        
        try:
            result = chain.invoke({
                "model_title": formal_model.model_title,
                "parameters": params_text,
                "targets": targets_text,
                "strategy": strategy_text
            })
            
            data = json.loads(result.content)
            calibrated_params = [CalibratedParameter(**p) for p in data.get("calibrated_parameters", [])]
            
            return calibrated_params
        
        except Exception as e:
            print(f"    Error calibrating parameters: {e}")
            return []
    
    def _generate_model_moments(
        self,
        formal_model: FormalMathematicalModel,
        calibrated_parameters: List[CalibratedParameter],
        empirical_targets: List[EmpiricalTarget]
    ) -> List[ModelMoment]:
        """Generate model moments from calibrated model."""
        
        params_text = "\n".join([
            f"- {p.parameter_symbol} = {p.calibrated_value}"
            for p in calibrated_parameters
        ])
        
        targets_text = "\n".join([
            f"- {t.target_id}: {t.target_name} = {t.empirical_value}"
            for t in empirical_targets
        ])
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are an expert at computing model-implied moments from calibrated economic models."),
            ("user", """Compute model-implied moments for the calibrated model.

Model: {model_title}

Calibrated Parameters:
{parameters}

Empirical Targets:
{targets}

For each target, compute the model-implied value and errors.
Provide:
- moment_name: Name of the moment
- model_value: Value from calibrated model (realistic)
- empirical_value: Empirical target value
- absolute_error: |model_value - empirical_value|
- relative_error: |(model_value - empirical_value) / empirical_value| * 100
- fit_quality: Excellent (<5% error), Good (5-15%), Fair (15-30%), Poor (>30%)

Return as JSON with "moments" array.
Example: {{
  "moments": [
    {{
      "moment_name": "Capital-output ratio",
      "model_value": 2.48,
      "empirical_value": 2.5,
      "absolute_error": 0.02,
      "relative_error": 0.8,
      "fit_quality": "Excellent"
    }}
  ]
}}

Respond with ONLY the JSON object, no other text.
""")
        ])
        
        chain = prompt | self.llm
        
        try:
            result = chain.invoke({
                "model_title": formal_model.model_title,
                "parameters": params_text,
                "targets": targets_text
            })
            
            data = json.loads(result.content)
            moments = [ModelMoment(**m) for m in data.get("moments", [])]
            
            return moments
        
        except Exception as e:
            print(f"    Error generating moments: {e}")
            return []
    
    def _compute_fit_metrics(
        self,
        model_moments: List[ModelMoment],
        empirical_targets: List[EmpiricalTarget]
    ) -> FitMetrics:
        """Compute overall fit metrics."""
        
        if not model_moments:
            return FitMetrics(
                total_targets=len(empirical_targets),
                targets_matched=0,
                mean_absolute_error=0.0,
                mean_relative_error=0.0,
                rmse=0.0,
                fit_score=0.0,
                fit_assessment="No moments computed"
            )
        
        # Count well-matched targets (relative error < 15%)
        targets_matched = sum(1 for m in model_moments if m.relative_error < 15.0)
        
        # Compute mean errors
        mean_abs_error = sum(m.absolute_error for m in model_moments) / len(model_moments)
        mean_rel_error = sum(m.relative_error for m in model_moments) / len(model_moments)
        
        # Compute RMSE
        rmse = (sum(m.absolute_error ** 2 for m in model_moments) / len(model_moments)) ** 0.5
        
        # Compute fit score (0-1, higher is better)
        # Based on mean relative error: 0% error = 1.0, 50% error = 0.0
        fit_score = max(0.0, min(1.0, 1.0 - (mean_rel_error / 50.0)))
        
        # Assessment
        if fit_score >= 0.9:
            assessment = "Excellent fit - model matches data very well"
        elif fit_score >= 0.75:
            assessment = "Good fit - model captures key features"
        elif fit_score >= 0.6:
            assessment = "Fair fit - reasonable match with room for improvement"
        else:
            assessment = "Poor fit - significant discrepancies remain"
        
        return FitMetrics(
            total_targets=len(empirical_targets),
            targets_matched=targets_matched,
            mean_absolute_error=round(mean_abs_error, 4),
            mean_relative_error=round(mean_rel_error, 2),
            rmse=round(rmse, 4),
            fit_score=round(fit_score, 3),
            fit_assessment=assessment
        )
    
    def _synthesize_calibrated_model(
        self,
        formal_model: FormalMathematicalModel,
        empirical_targets: List[EmpiricalTarget],
        calibration_strategy: CalibrationStrategy,
        calibrated_parameters: List[CalibratedParameter],
        model_moments: List[ModelMoment],
        fit_metrics: FitMetrics
    ) -> CalibratedModel:
        """Synthesize complete calibrated model."""
        
        model_title = f"Calibrated Model: {formal_model.based_on_framework}"
        
        # Generate calibration summary
        calibration_summary = f"""
This calibrated model is based on '{formal_model.model_title}'.
Calibration used {calibration_strategy.strategy_type} strategy with {len(empirical_targets)} empirical targets.
{len(calibrated_parameters)} parameters were calibrated, achieving a fit score of {fit_metrics.fit_score:.3f}.
The model matches {fit_metrics.targets_matched} out of {fit_metrics.total_targets} targets well (< 15% error).
Overall assessment: {fit_metrics.fit_assessment}
        """.strip()
        
        # Calibration notes
        notes = f"""
Calibration Strategy: {calibration_strategy.description}
Identification: {calibration_strategy.identification_notes}

Key Calibrated Parameters:
{chr(10).join([f"- {p.parameter_symbol} = {p.calibrated_value}: {p.justification}" for p in calibrated_parameters[:5]])}

Model Performance:
- Mean Relative Error: {fit_metrics.mean_relative_error:.2f}%
- RMSE: {fit_metrics.rmse:.4f}
- Targets Well-Matched: {fit_metrics.targets_matched}/{fit_metrics.total_targets}
        """.strip()
        
        # Robustness checks
        robustness_checks = [
            "Sensitivity analysis: vary key parameters by ±10% and check moment stability",
            "Alternative calibration targets: use different data sources or time periods",
            "Specification tests: check if model predictions hold out-of-sample",
            "Monte Carlo analysis: assess parameter uncertainty through bootstrap",
            "Cross-validation: split sample and validate on held-out data"
        ]
        
        # Next steps
        next_steps = [
            "Implement model in computational software (MATLAB/Python/Julia)",
            "Solve for steady state and check stability",
            "Compute impulse response functions to shocks",
            "Perform policy experiments and counterfactuals",
            "Validate model predictions against additional moments",
            "Prepare model for estimation using full likelihood or SMM"
        ]
        
        calibrated_model = CalibratedModel(
            model_title=model_title,
            based_on_model=formal_model.model_title,
            calibration_summary=calibration_summary,
            empirical_targets=empirical_targets,
            calibration_strategy=calibration_strategy,
            calibrated_parameters=calibrated_parameters,
            model_moments=model_moments,
            fit_metrics=fit_metrics,
            calibration_notes=notes,
            robustness_checks=robustness_checks,
            next_steps=next_steps,
            metadata={
                "timestamp": datetime.now().isoformat(),
                "num_targets": len(empirical_targets),
                "num_calibrated_params": len(calibrated_parameters),
                "fit_score": fit_metrics.fit_score
            }
        )
        
        return calibrated_model


# ========== ORCHESTRATOR ==========

class CalibrationOrchestrator:
    """Orchestrator for the calibration stage."""
    
    def __init__(self, openai_api_key: Optional[str] = None):
        self.api_key = openai_api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError("OpenAI API key is required.")
        
        self.calibrator = Calibrator(self.api_key)
        self.calibration_output: Optional[CalibrationOutput] = None
    
    def run_calibration_pipeline(
        self,
        model_design_output: Dict
    ) -> CalibrationOutput:
        """Run the complete calibration pipeline."""
        
        print(f"\n{'='*70}")
        print(f"CALIBRATION PIPELINE")
        print(f"{'='*70}")
        
        # Parse formal models
        formal_models_data = model_design_output.get('formal_models', [])
        formal_models = [FormalMathematicalModel(**m) for m in formal_models_data]
        
        print(f"Formal Models: {len(formal_models)}")
        print(f"{'='*70}\n")
        
        # Calibrate models
        calibrated_models = []
        for formal_model in formal_models:
            calibrated_model = self.calibrator.calibrate_model(formal_model)
            calibrated_models.append(calibrated_model)
        
        # Create output
        self.calibration_output = CalibrationOutput(
            formal_models=formal_models,
            calibrated_models=calibrated_models,
            metadata={
                "timestamp": datetime.now().isoformat(),
                "num_models": len(formal_models),
                "num_calibrated": len(calibrated_models),
                "average_fit_score": sum(m.fit_metrics.fit_score for m in calibrated_models) / len(calibrated_models) if calibrated_models else 0.0
            }
        )
        
        print(f"\n{'='*70}")
        print(f"PIPELINE COMPLETE")
        print(f"{'='*70}")
        print(f"Calibrated Models: {len(calibrated_models)}")
        print(f"Average Fit Score: {self.calibration_output.metadata['average_fit_score']:.3f}")
        print(f"{'='*70}\n")
        
        return self.calibration_output
    
    def save_calibration_output(self, filename: str = "calibration_output.json"):
        """Save calibration output to JSON."""
        if not self.calibration_output:
            print("No calibration output to save")
            return
        
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(self.calibration_output.model_dump(), f, indent=2)
        
        print(f"[Orchestrator] Calibration output saved to {filename}")
    
    def save_calibration_text(self, filename: str = "calibrated_models.txt"):
        """Save calibrated models in readable text format."""
        if not self.calibration_output:
            print("No calibration output to save")
            return
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write("="*70 + "\n")
            f.write("CALIBRATED ECONOMIC MODELS\n")
            f.write("="*70 + "\n\n")
            
            for i, model in enumerate(self.calibration_output.calibrated_models, 1):
                f.write(f"MODEL {i}: {model.model_title}\n")
                f.write("="*70 + "\n\n")
                
                f.write(f"SUMMARY:\n{model.calibration_summary}\n\n")
                
                f.write(f"EMPIRICAL TARGETS ({len(model.empirical_targets)}):\n")
                for target in model.empirical_targets:
                    f.write(f"  {target.target_id}. {target.target_name}\n")
                    f.write(f"     Empirical Value: {target.empirical_value}\n")
                    f.write(f"     Source: {target.empirical_source}\n")
                    f.write(f"     Importance: {target.importance}\n\n")
                
                f.write(f"CALIBRATION STRATEGY:\n")
                f.write(f"  Type: {model.calibration_strategy.strategy_type}\n")
                f.write(f"  {model.calibration_strategy.description}\n\n")
                
                f.write(f"CALIBRATED PARAMETERS ({len(model.calibrated_parameters)}):\n")
                for param in model.calibrated_parameters:
                    f.write(f"  {param.parameter_symbol} = {param.calibrated_value}\n")
                    f.write(f"     {param.parameter_name}\n")
                    f.write(f"     Method: {param.calibration_method}\n")
                    f.write(f"     Justification: {param.justification}\n")
                    f.write(f"     Sensitivity: {param.sensitivity}\n\n")
                
                f.write(f"MODEL MOMENTS ({len(model.model_moments)}):\n")
                for moment in model.model_moments:
                    f.write(f"  {moment.moment_name}\n")
                    f.write(f"     Model: {moment.model_value:.4f} | Empirical: {moment.empirical_value:.4f}\n")
                    f.write(f"     Error: {moment.relative_error:.2f}% | Fit: {moment.fit_quality}\n\n")
                
                f.write(f"FIT METRICS:\n")
                f.write(f"  Fit Score: {model.fit_metrics.fit_score:.3f}\n")
                f.write(f"  Mean Relative Error: {model.fit_metrics.mean_relative_error:.2f}%\n")
                f.write(f"  RMSE: {model.fit_metrics.rmse:.4f}\n")
                f.write(f"  Targets Matched: {model.fit_metrics.targets_matched}/{model.fit_metrics.total_targets}\n")
                f.write(f"  Assessment: {model.fit_metrics.fit_assessment}\n\n")
                
                f.write(f"ROBUSTNESS CHECKS:\n")
                for check in model.robustness_checks:
                    f.write(f"  - {check}\n")
                f.write("\n")
                
                f.write(f"NEXT STEPS:\n")
                for step in model.next_steps:
                    f.write(f"  - {step}\n")
                f.write("\n")
                
                f.write("-"*70 + "\n\n")
        
        print(f"[Orchestrator] Calibrated models saved to {filename}")
    
    def save_parameters_csv(self, filename: str = "calibrated_parameters.csv"):
        """Save calibrated parameters to CSV."""
        if not self.calibration_output:
            print("No calibration output to save")
            return
        
        rows = []
        for model in self.calibration_output.calibrated_models:
            for param in model.calibrated_parameters:
                rows.append({
                    'model': model.model_title,
                    'parameter_symbol': param.parameter_symbol,
                    'parameter_name': param.parameter_name,
                    'calibrated_value': param.calibrated_value,
                    'calibration_method': param.calibration_method,
                    'literature_range': param.literature_range,
                    'sensitivity': param.sensitivity
                })
        
        df = pd.DataFrame(rows)
        df.to_csv(filename, index=False)
        print(f"[Orchestrator] Parameters saved to {filename}")


def main():
    """Main function for calibration stage."""
    
    # Change to script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)
    print(f"Working directory: {os.getcwd()}\n")
    
    # Load model design output
    design_file = input("Enter path to model design output JSON (from Stage 2): ").strip()
    
    if not os.path.exists(design_file):
        print(f"Error: {design_file} not found!")
        return
    
    # Load data
    with open(design_file, 'r', encoding='utf-8') as f:
        model_design_output = json.load(f)
    
    # Run pipeline
    orchestrator = CalibrationOrchestrator()
    calibration_output = orchestrator.run_calibration_pipeline(model_design_output)
    
    # Save outputs
    orchestrator.save_calibration_output("calibration_output.json")
    orchestrator.save_calibration_text("calibrated_models.txt")
    orchestrator.save_parameters_csv("calibrated_parameters.csv")
    
    # Print summary
    print("\n" + "="*70)
    print("CALIBRATION SUMMARY")
    print("="*70)
    for i, model in enumerate(calibration_output.calibrated_models, 1):
        print(f"\n{i}. {model.model_title}")
        print(f"   Fit Score: {model.fit_metrics.fit_score:.3f}")
        print(f"   Mean Error: {model.fit_metrics.mean_relative_error:.2f}%")
        print(f"   Targets Matched: {model.fit_metrics.targets_matched}/{model.fit_metrics.total_targets}")
        print(f"   Assessment: {model.fit_metrics.fit_assessment}")
    print("\n" + "="*70)


if __name__ == "__main__":
    main()
